# Site
name: "Video"
title: "BSafes Video"
description: "Introducing BSafes Collaborative Note-Taking with 256-Bit End-to-End Encryption"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
bsafesURL: 'https://www.bsafes.com'
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 
include: ["_pages"]
permalink: /:title/
company: "Wu-Nan Technology Inc."

# Authors
authors:
  EJServiceKiosk:
    name: EJServiceKiosk 
    display_name: EJServiceKiosk
    avatar: https://statics.bsafes.com/images/megaphone-2374502_640.png 
    email: support@bsafes.com
    web: https://www.fiverr.com/ejservicekiosk?source=order_page_summary_seller_link
    twitter: 
    description: "I'm an Internet Culture expert"
  fahadkhan1990:
    name: fahadkhan1990 
    display_name: fahadkhan1990 
    avatar: https://fiverr-res.cloudinary.com/t_profile_original,q_auto,f_auto/attachments/profile/photo/92250c016d4dde599ba633399fa89c35-1524519092694/d24b9fb4-00d3-4758-96d4-15ed0f17c81a.jpg 
    email: support@bsafes.com
    web: https://www.fiverr.com/fahadkhan1990?source=order_page_summary_seller_link 
    twitter:
    description: "Hey, I am Fahad and I have done M.Phil in Computer Science. I am a tech geek and creative writer."
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
